{
 "title": "Tweet-api",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_request_operations_total[3m])"
    }
   ]
  },
  {
   "title": "Tweets rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(tweets_count[2m])" }
   ]
  },
  {
   "title": "Users Registration rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(users_count[2m])" }
   ]
  }
 ]
}